# Generated by Django 3.1.14 on 2022-11-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0015_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, null=True, related_name='weak_against', to='pokemon_entities.PokemonElementType', verbose_name='Strong against elements'),
        ),
    ]
